export const pathname = {
	home: "/",
	signUp: "/sign-up",
	signIn: "/sign-in",
	forgotPassword: "/forgot-password",
	changePassword: "/change-password",
	changePasswordSuccessfully: "/forgot-password-successfully",
	profile: "/profile",
	languages: "/language",
	vocabularySet: "/vocabulary-set",
	createCourse: "/create-course",
	listCourse: "/list-course",
	courseVocabulary: "/course-vocabulary/:courseId",
	editCourse: "/edit-course/:courseId",
	listExamples: "/list-examples/:courseId",
	addByLevels: "/add-by-levels",
	courseBusiness: "/course-business/:courseId",
	courseInformation: "/course-information/:courseId",
	payment: "/course-purchase/:courseId",
	flashCard: "/flash-card",
	learnProcess: "/learn-process",
	listExercise: "/list-exercise/:courseId",
	personalStatics: "/personal-statics",
	learn: "/learn",
};
