export const pathname = {
	home: "/",
	signUp: "/sign-up",
	signIn: "/sign-in",
	forgotPassword: "/forgot-password",
	changePassword: "/change-password",
	changePasswordSuccessfully: "/forgot-password-successfully",
	profile: "/profile",
	languages: "/language",
	vocabularySet: "/vocabulary-set",
	createCourse: "/create-course",
	listCourse: "/list-course",
	addVocab: "/add-vocab/:courseId",
	editCourse: "/edit-course",
	listExamples: "/list-examples/:courseId",
	addByLevels: "/add-by-levels",
	courseBusiness: "/course-business",
	courseInformation: "/course-information/:courseId",
	payment: "/course-purchase",
};
