const queryKeys = {
	courseComment: "course-comment",
	courseContent: "course-content",
	languages: "languages",
	userState: "user-state",
	courseVocabulary: "course-vocabulary",
	courseInfo: "course-info",
	levelCourse: "level-course",
	exampleByWord: "example-by-word",
	courseLanguages: "course-languages",
	flashCard: "flash-card",
	coursePrice: "course-price",
	enrollmentInfo: "enrollment-info",
	level: "level",
	exercise: "course-exercise",
	finishedCourses: "finished-course",
	unfinishedCourses: "unfinished-course",
	ownCourses: "own-course",
	checkOwnCourse: "check-own-course",
	competitorPoints: "competitor-points",
	enrollmentProgress: "enrollment-progress",
	courseRate: "course-rate",
	courseRevenue: "course-revenue",
	userStreak: "user-streak",
	userStatistic: "user-statistic",
	mostPopularCourse: "most-popular-course",
	mostDiscountCourse: "most-discount-course",
	allLearntWords: "all-learnt-words",
	markedWords: "marked-words",
};

export { queryKeys };
